shell /bin/zsh
symbol_map U+4E00-U+9FFF,U+3000-U+303F,U+FF00-U+FFEF Noto Sans Mono CJK SC
font_family JetBrainsMono Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
modify_font cell_width 100%
font_size 12

# Color scheme ported from Alacritty
background_opacity 0.6
background #000000
foreground #ffffff
selection_foreground #ffffff
selection_background #009900

# Normal colors
color0 #000000
color1 #e92f2f
color2 #0ed839
color3 #fbfbb1
color4 #4ba3ff
color5 #f996e2
color6 #62ffe7
color7 #ababab

# Bright colors
color8 #343434
color9 #e92f2f
color10 #0ed839
color11 #fbfbd0
color12 #5eacff
color13 #f996e2
color14 #23edda
color15 #f9f9f9

# Disable close confirmation
confirm_os_window_close 0
