#!/bin/bash
# ==============================================================================
# Script Name: change_wallpaper.sh
# Description: Synchronously changes the desktop wallpaper for both the swaybg 
#              and awww backends in the Niri environment.
# Author: Generated by 剪秋萝
# ==============================================================================

# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

# Define the absolute paths for the wallpaper directories
readonly DIR_SWAYBG="/home/lightwall/swaybg_wallpapers"
readonly DIR_AWWW="/home/lightwall/awww_wallpapers"

# Define the absolute paths for the state and cache files
readonly STATE_FILE="$HOME/.cache/wallpaper_index"
readonly SWAYBG_CACHE="$HOME/.cache/current_swaybg_img"

# ------------------------------------------------------------------------------
# Initialization
# ------------------------------------------------------------------------------

# Ensure that the necessary wallpaper directories exist
mkdir -p "$DIR_SWAYBG"
mkdir -p "$DIR_AWWW"

# Read the current index from the state file. Defaults to 0 if the file does not exist.
if [[ -f "$STATE_FILE" ]]; then
    INDEX=$(cat "$STATE_FILE")
else
    INDEX=0
fi

# ------------------------------------------------------------------------------
# File Loading
# ------------------------------------------------------------------------------

# Enable nullglob to handle empty directories gracefully
shopt -s nullglob

# Load the file paths into arrays, sorted alphabetically
FILES_SWAYBG=("$DIR_SWAYBG"/*)
FILES_AWWW=("$DIR_AWWW"/*)

# Disable nullglob to revert to default shell behavior
shopt -u nullglob

# ------------------------------------------------------------------------------
# Validation
# ------------------------------------------------------------------------------

# Verify that both directories contain at least one image
if [[ ${#FILES_SWAYBG[@]} -eq 0 ]] || [[ ${#FILES_AWWW[@]} -eq 0 ]]; then
    echo "Error: One or both wallpaper directories are empty." >&2
    exit 1
fi

# ------------------------------------------------------------------------------
# Index Calculation
# ------------------------------------------------------------------------------

# Increment the global index
INDEX=$((INDEX + 1))

# Calculate the specific array indices using modulo to ensure safe cycling 
# regardless of differing array lengths.
IDX_SWAYBG=$((INDEX % ${#FILES_SWAYBG[@]}))
IDX_AWWW=$((INDEX % ${#FILES_AWWW[@]}))

# Persist the updated global index to the state file
echo "$INDEX" > "$STATE_FILE"

# ------------------------------------------------------------------------------
# Execution
# ------------------------------------------------------------------------------

# Retrieve the absolute file paths for the next wallpapers
IMG_SWAYBG="${FILES_SWAYBG[$IDX_SWAYBG]}"
IMG_AWWW="${FILES_AWWW[$IDX_AWWW]}"

# 1. Update the awww workspace wallpaper with a faster, smoother transition
awww img "$IMG_AWWW" --transition-fps 60 --transition-type fade --transition-duration 0.8

# 2. Update the swaybg background wallpaper (Seamless replacement to avoid black flash)
echo "$IMG_SWAYBG" > "$SWAYBG_CACHE"

# Start the new swaybg process in the background
swaybg -i "$IMG_SWAYBG" -m fill &
NEW_PID=$!

# Wait a tiny fraction of a second for the new image to render
sleep 0.1

# Find and kill the old swaybg processes gracefully
for pid in $(pgrep -x swaybg); do
    if [ "$pid" != "$NEW_PID" ]; then
        kill "$pid"
    fi
done

exit 0
